name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and run Docker Compose
        run: |
          cd ./docker
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d
