name: Deploy PHP Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PHP Server
        run: php -S localhost:8000 &

      - name: Wait for PHP Server
        run: sleep 3

      - name: Test PHP Application
        run: curl http://localhost:8000
